sudo: required

os:
  - linux
  - osx

services:
    - docker

language: rust
rust:
    - stable

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo install cross ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rustup target add i686-apple-darwin ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cross build --release --target aarch64-linux-android ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cross build --release --target arm-linux-androideabi ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cross build --release --target i686-linux-android ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cross build --release --target i686-pc-windows-gnu ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cross build --release --target i686-unknown-linux-gnu ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cross build --release --target x86_64-pc-windows-gnu ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cross build --release --target x86_64-unknown-linux-gnu ; fi
# TODO(kgreenek): Figure out how to support iOS builds.
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cargo build --release --target aarch64-apple-ios ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cargo build --release --target armv7-apple-ios ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cargo build --release --target armv7s-apple-ios ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cargo build --release --target i386-apple-ios ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cargo build --release --target x86_64-apple-ios ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cargo build --release --target i686-apple-darwin ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cargo build --release --target x86_64-apple-darwin ; fi
