sudo: required
services:
  - docker
language: rust
rust:
  - stable
#  - beta
#  - nightly
os:
  - linux
  - osx
env:
  - RZERO_TARGET=x86_64-unknown-linux-gnu
  - RZERO_TARGET=i686-unknown-linux-gnu
  - RZERO_TARGET=x86_64-pc-windows-gnu
  - RZERO_TARGET=i686-pc-windows-gnu
  - RZERO_TARGET=aarch64-linux-android
  - RZERO_TARGET=arm-linux-androideabi
  - RZERO_TARGET=i686-linux-android
  - RZERO_TARGET=x86_64-apple-darwin
  - RZERO_TARGET=i686-apple-darwin
  - RZERO_TARGET=universal-apple-ios
matrix:
#  allow_failures:
#    - rust: nightly
  exclude:
    - os: osx
      env: RZERO_TARGET=x86_64-unknown-linux-gnu
    - os: osx
      env: RZERO_TARGET=i686-unknown-linux-gnu
    - os: osx
      env: RZERO_TARGET=x86_64-pc-windows-gnu
    - os: osx
      env: RZERO_TARGET=i686-pc-windows-gnu
    - os: osx
      env: RZERO_TARGET=aarch64-linux-android
    - os: osx
      env: RZERO_TARGET=arm-linux-androideabi
    - os: osx
      env: RZERO_TARGET=i686-linux-android
    - os: linux
      env: RZERO_TARGET=x86_64-apple-darwin
    - os: linux
      env: RZERO_TARGET=i686-apple-darwin
    - os: linux
      env: RZERO_TARGET=universal-apple-ios
cache: cargo
install:
  - ./travis/install.sh
script:
  - ./travis/build.sh debug
before_deploy: ./travis/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: aZuE8gOuK/1K4UWeUQdu4HR6g/nrs9YjbyZOCZbhwdomi63EbAUxUfd7w4ZWYiGR0XUE7UvM4NTaUj2il0x9A65Wf4ekcNutfPYL1qDHuD/6UBPZtK9QST3uzmBeZ+WYsZRC5jLtdEI7yb8/luzCi6yDmR/NgEDAMEqTcN1j4uHNbszFlZ7yMTBNPkMvLtjySKs8FICMJENJh65qbswfS2Ditm2jZK02SvUfQNT0bLNVVTVMW5rAIACHAe+04ILhNPXr4Ns/Cw0UT2lWbPGaIcYDRuQdS3JLaIL6HgkmLAK8g/S7MwY8B6A88GgAhd8nvm6bGMEWOy9xEJZMPVHhGZzWK8oARHVFxIUgc6H1WlYy3djKzINEK/aA9BnunZ7Y8908jyTPUJL9JzdUWrpKNXyVaMC6bMoVjHXyapucxVGcgIxrBngTuHMnuBlYvSJq1Ip2fVKQXec5NLDCW26RXDme9W+hav52uZRMHBCAp4zmREznHTmLTgtONwS+lxNp+DT14gx1plMgcGcRirbjHwjr/2fyrKDI8WtJnH+c6HYcPOQbM8Q+VRNqXG8XLqDUVX7GJT06n/DyWCKBCxv8LfipKBVhQwpYAWVOrLHrw7rvI0jRRvFKiZI00ep/Gn+8j8SiVbzfkn/+d0T2YJNdlECCihhyYAQ/4T6uTa8UoBI=
  file_glob: true
  file: "deploy/*.zip"
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_RUST_VERSION = stable
