[package]
name = "rzero"
description = "rzero"
version = "0.1.0"
authors = ["Kevin Greene <kgreenek@gmail.com>"]

[dependencies]

[lib]
name = "rzero"
crate-type = ["staticlib", "cdylib", "rlib"]

[profile.release]
lto = true

[dev-dependencies]
sample = "0.9.0"
hound = "2.0"
clap = "2.27"
