[package]
name = "draw_wav"
version = "0.1.0"
authors = ["Kevin Greene <kgreenek@gmail.com>"]

[dependencies]
clap = "2.27"
hound = "2.0"
rustplotlib = "0.0.4"
rzero = { path = ".." }
sample = "0.9.0"

[profile.release]
lto = true
